### ISSUE TITLE
Package on conda-forge?

### ISSUE THREAD

**Issue by jpivarski** [intake/awkward-pandas#32]
As mentioned on hsf-training/hsf-training-scikit-hep-webpage#49, awkward-pandas doesn't have a package on conda-forge yet. For the time being, we can install it with pip, but it would be better if everything could be installed with the same dependency manager.

**Comment by douglasdavis** [comment]
tracking here https://github.com/conda-forge/staged-recipes/pull/23612

**Comment by douglasdavis** [comment]
in :+1:
